services:
  fac-csconsts:
    container_name: 'facs-csconsts'
    image: 'ghcr.io/lnls-sirius/control-system-constants:${RELEASE_TAG}'
    build:
      context: .
      args:
        RELEASE_TAG: ${RELEASE_TAG}
      labels:
        - "br.com.lnls-sirius.department=FAC"
    ports:
      - 20080:20080
