# This is a python3 file:
#     - The object defined here is a python3 dictionary.
#     - It can be imported into python3 code with the code:
#         `return_dict = ast.literal_eval('/pathto/high-level-triggers.py')`
#     where `ast` is a python3 module available in `pip3`
#
# This file define the triggers used in Sirius operation system and
# maps them with several important properties.
{
    # ### Magnets ###
    'SI-Glob:TI-Mags-Corrs': {
        'database': {
            'Src': {'enums': ('OrbSI', 'Cycle')},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 3920},
            'Duration': {'value': 2000},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'SI-01M1:PS-CH:BCKPLN', 'SI-01M1:PS-CV:BCKPLN',
            'SI-01M2:PS-CH:BCKPLN', 'SI-01M2:PS-CV:BCKPLN',
            'SI-01C1:PS-CH:BCKPLN', 'SI-01C1:PS-CV:BCKPLN',
            'SI-01C2:PS-CH:BCKPLN', 'SI-01C2:PS-CV-1:BCKPLN',
            'SI-01C2:PS-CV-2:BCKPLN',
            'SI-01C3:PS-CH:BCKPLN', 'SI-01C3:PS-CV-1:BCKPLN',
            'SI-01C3:PS-CV-2:BCKPLN',
            'SI-01C4:PS-CH:BCKPLN', 'SI-01C4:PS-CV:BCKPLN',

            'SI-02M1:PS-CH:BCKPLN', 'SI-02M1:PS-CV:BCKPLN',
            'SI-02M2:PS-CH:BCKPLN', 'SI-02M2:PS-CV:BCKPLN',
            'SI-02C1:PS-CH:BCKPLN', 'SI-02C1:PS-CV:BCKPLN',
            'SI-02C2:PS-CH:BCKPLN', 'SI-02C2:PS-CV-1:BCKPLN',
            'SI-02C2:PS-CV-2:BCKPLN',
            'SI-02C3:PS-CH:BCKPLN', 'SI-02C3:PS-CV-1:BCKPLN',
            'SI-02C3:PS-CV-2:BCKPLN',
            'SI-02C4:PS-CH:BCKPLN', 'SI-02C4:PS-CV:BCKPLN',

            'SI-03M1:PS-CH:BCKPLN', 'SI-03M1:PS-CV:BCKPLN',
            'SI-03M2:PS-CH:BCKPLN', 'SI-03M2:PS-CV:BCKPLN',
            'SI-03C1:PS-CH:BCKPLN', 'SI-03C1:PS-CV:BCKPLN',
            'SI-03C2:PS-CH:BCKPLN', 'SI-03C2:PS-CV-1:BCKPLN',
            'SI-03C2:PS-CV-2:BCKPLN',
            'SI-03C3:PS-CH:BCKPLN', 'SI-03C3:PS-CV-1:BCKPLN',
            'SI-03C3:PS-CV-2:BCKPLN',
            'SI-03C4:PS-CH:BCKPLN', 'SI-03C4:PS-CV:BCKPLN',

            'SI-04M1:PS-CH:BCKPLN', 'SI-04M1:PS-CV:BCKPLN',
            'SI-04M2:PS-CH:BCKPLN', 'SI-04M2:PS-CV:BCKPLN',
            'SI-04C1:PS-CH:BCKPLN', 'SI-04C1:PS-CV:BCKPLN',
            'SI-04C2:PS-CH:BCKPLN', 'SI-04C2:PS-CV-1:BCKPLN',
            'SI-04C2:PS-CV-2:BCKPLN',
            'SI-04C3:PS-CH:BCKPLN', 'SI-04C3:PS-CV-1:BCKPLN',
            'SI-04C3:PS-CV-2:BCKPLN',
            'SI-04C4:PS-CH:BCKPLN', 'SI-04C4:PS-CV:BCKPLN',

            'SI-05M1:PS-CH:BCKPLN', 'SI-05M1:PS-CV:BCKPLN',
            'SI-05M2:PS-CH:BCKPLN', 'SI-05M2:PS-CV:BCKPLN',
            'SI-05C1:PS-CH:BCKPLN', 'SI-05C1:PS-CV:BCKPLN',
            'SI-05C2:PS-CH:BCKPLN', 'SI-05C2:PS-CV-1:BCKPLN',
            'SI-05C2:PS-CV-2:BCKPLN',
            'SI-05C3:PS-CH:BCKPLN', 'SI-05C3:PS-CV-1:BCKPLN',
            'SI-05C3:PS-CV-2:BCKPLN',
            'SI-05C4:PS-CH:BCKPLN', 'SI-05C4:PS-CV:BCKPLN',

            'SI-06M1:PS-CH:BCKPLN', 'SI-06M1:PS-CV:BCKPLN',
            'SI-06M2:PS-CH:BCKPLN', 'SI-06M2:PS-CV:BCKPLN',
            'SI-06C1:PS-CH:BCKPLN', 'SI-06C1:PS-CV:BCKPLN',
            'SI-06C2:PS-CH:BCKPLN', 'SI-06C2:PS-CV-1:BCKPLN',
            'SI-06C2:PS-CV-2:BCKPLN',
            'SI-06C3:PS-CH:BCKPLN', 'SI-06C3:PS-CV-1:BCKPLN',
            'SI-06C3:PS-CV-2:BCKPLN',
            'SI-06C4:PS-CH:BCKPLN', 'SI-06C4:PS-CV:BCKPLN',

            'SI-07M1:PS-CH:BCKPLN', 'SI-07M1:PS-CV:BCKPLN',
            'SI-07M2:PS-CH:BCKPLN', 'SI-07M2:PS-CV:BCKPLN',
            'SI-07C1:PS-CH:BCKPLN', 'SI-07C1:PS-CV:BCKPLN',
            'SI-07C2:PS-CH:BCKPLN', 'SI-07C2:PS-CV-1:BCKPLN',
            'SI-07C2:PS-CV-2:BCKPLN',
            'SI-07C3:PS-CH:BCKPLN', 'SI-07C3:PS-CV-1:BCKPLN',
            'SI-07C3:PS-CV-2:BCKPLN',
            'SI-07C4:PS-CH:BCKPLN', 'SI-07C4:PS-CV:BCKPLN',

            'SI-08M1:PS-CH:BCKPLN', 'SI-08M1:PS-CV:BCKPLN',
            'SI-08M2:PS-CH:BCKPLN', 'SI-08M2:PS-CV:BCKPLN',
            'SI-08C1:PS-CH:BCKPLN', 'SI-08C1:PS-CV:BCKPLN',
            'SI-08C2:PS-CH:BCKPLN', 'SI-08C2:PS-CV-1:BCKPLN',
            'SI-08C2:PS-CV-2:BCKPLN',
            'SI-08C3:PS-CH:BCKPLN', 'SI-08C3:PS-CV-1:BCKPLN',
            'SI-08C3:PS-CV-2:BCKPLN',
            'SI-08C4:PS-CH:BCKPLN', 'SI-08C4:PS-CV:BCKPLN',

            'SI-09M1:PS-CH:BCKPLN', 'SI-09M1:PS-CV:BCKPLN',
            'SI-09M2:PS-CH:BCKPLN', 'SI-09M2:PS-CV:BCKPLN',
            'SI-09C1:PS-CH:BCKPLN', 'SI-09C1:PS-CV:BCKPLN',
            'SI-09C2:PS-CH:BCKPLN', 'SI-09C2:PS-CV-1:BCKPLN',
            'SI-09C2:PS-CV-2:BCKPLN',
            'SI-09C3:PS-CH:BCKPLN', 'SI-09C3:PS-CV-1:BCKPLN',
            'SI-09C3:PS-CV-2:BCKPLN',
            'SI-09C4:PS-CH:BCKPLN', 'SI-09C4:PS-CV:BCKPLN',

            'SI-10SB:PS-CH-1:BCKPLN', 'SI-10SB:PS-CH-2:BCKPLN',
            'SI-10SB:PS-CV-1:BCKPLN', 'SI-10SB:PS-CV-2:BCKPLN',
            'SI-10M1:PS-CH:BCKPLN', 'SI-10M1:PS-CV:BCKPLN',
            'SI-10M2:PS-CH:BCKPLN', 'SI-10M2:PS-CV:BCKPLN',
            'SI-10C1:PS-CH:BCKPLN', 'SI-10C1:PS-CV:BCKPLN',
            'SI-10C2:PS-CH:BCKPLN', 'SI-10C2:PS-CV-1:BCKPLN',
            'SI-10C2:PS-CV-2:BCKPLN',
            'SI-10C3:PS-CH:BCKPLN', 'SI-10C3:PS-CV-1:BCKPLN',
            'SI-10C3:PS-CV-2:BCKPLN',
            'SI-10C4:PS-CH:BCKPLN', 'SI-10C4:PS-CV:BCKPLN',

            'SI-11M1:PS-CH:BCKPLN', 'SI-11M1:PS-CV:BCKPLN',
            'SI-11M2:PS-CH:BCKPLN', 'SI-11M2:PS-CV:BCKPLN',
            'SI-11C1:PS-CH:BCKPLN', 'SI-11C1:PS-CV:BCKPLN',
            'SI-11C2:PS-CH:BCKPLN', 'SI-11C2:PS-CV-1:BCKPLN',
            'SI-11C2:PS-CV-2:BCKPLN',
            'SI-11C3:PS-CH:BCKPLN', 'SI-11C3:PS-CV-1:BCKPLN',
            'SI-11C3:PS-CV-2:BCKPLN',
            'SI-11C4:PS-CH:BCKPLN', 'SI-11C4:PS-CV:BCKPLN',

            'SI-12M1:PS-CH:BCKPLN', 'SI-12M1:PS-CV:BCKPLN',
            'SI-12M2:PS-CH:BCKPLN', 'SI-12M2:PS-CV:BCKPLN',
            'SI-12C1:PS-CH:BCKPLN', 'SI-12C1:PS-CV:BCKPLN',
            'SI-12C2:PS-CH:BCKPLN', 'SI-12C2:PS-CV-1:BCKPLN',
            'SI-12C2:PS-CV-2:BCKPLN',
            'SI-12C3:PS-CH:BCKPLN', 'SI-12C3:PS-CV-1:BCKPLN',
            'SI-12C3:PS-CV-2:BCKPLN',
            'SI-12C4:PS-CH:BCKPLN', 'SI-12C4:PS-CV:BCKPLN',

            'SI-13M1:PS-CH:BCKPLN', 'SI-13M1:PS-CV:BCKPLN',
            'SI-13M2:PS-CH:BCKPLN', 'SI-13M2:PS-CV:BCKPLN',
            'SI-13C1:PS-CH:BCKPLN', 'SI-13C1:PS-CV:BCKPLN',
            'SI-13C2:PS-CH:BCKPLN', 'SI-13C2:PS-CV-1:BCKPLN',
            'SI-13C2:PS-CV-2:BCKPLN',
            'SI-13C3:PS-CH:BCKPLN', 'SI-13C3:PS-CV-1:BCKPLN',
            'SI-13C3:PS-CV-2:BCKPLN',
            'SI-13C4:PS-CH:BCKPLN', 'SI-13C4:PS-CV:BCKPLN',

            'SI-14SB:PS-CH-1:BCKPLN', 'SI-14SB:PS-CH-2:BCKPLN',
            'SI-14M1:PS-CH:BCKPLN', 'SI-14M1:PS-CV:BCKPLN',
            'SI-14M2:PS-CH:BCKPLN', 'SI-14M2:PS-CV:BCKPLN',
            'SI-14C1:PS-CH:BCKPLN', 'SI-14C1:PS-CV:BCKPLN',
            'SI-14C2:PS-CH:BCKPLN', 'SI-14C2:PS-CV-1:BCKPLN',
            'SI-14C2:PS-CV-2:BCKPLN',
            'SI-14C3:PS-CH:BCKPLN', 'SI-14C3:PS-CV-1:BCKPLN',
            'SI-14C3:PS-CV-2:BCKPLN',
            'SI-14C4:PS-CH:BCKPLN', 'SI-14C4:PS-CV:BCKPLN',

            'SI-15M1:PS-CH:BCKPLN', 'SI-15M1:PS-CV:BCKPLN',
            'SI-15M2:PS-CH:BCKPLN', 'SI-15M2:PS-CV:BCKPLN',
            'SI-15C1:PS-CH:BCKPLN', 'SI-15C1:PS-CV:BCKPLN',
            'SI-15C2:PS-CH:BCKPLN', 'SI-15C2:PS-CV-1:BCKPLN',
            'SI-15C2:PS-CV-2:BCKPLN',
            'SI-15C3:PS-CH:BCKPLN', 'SI-15C3:PS-CV-1:BCKPLN',
            'SI-15C3:PS-CV-2:BCKPLN',
            'SI-15C4:PS-CH:BCKPLN', 'SI-15C4:PS-CV:BCKPLN',

            'SI-16M1:PS-CH:BCKPLN', 'SI-16M1:PS-CV:BCKPLN',
            'SI-16M2:PS-CH:BCKPLN', 'SI-16M2:PS-CV:BCKPLN',
            'SI-16C1:PS-CH:BCKPLN', 'SI-16C1:PS-CV:BCKPLN',
            'SI-16C2:PS-CH:BCKPLN', 'SI-16C2:PS-CV-1:BCKPLN',
            'SI-16C2:PS-CV-2:BCKPLN',
            'SI-16C3:PS-CH:BCKPLN', 'SI-16C3:PS-CV-1:BCKPLN',
            'SI-16C3:PS-CV-2:BCKPLN',
            'SI-16C4:PS-CH:BCKPLN', 'SI-16C4:PS-CV:BCKPLN',

            'SI-17SA:PS-CH-1:BCKPLN', 'SI-17SA:PS-CH-2:BCKPLN',
            'SI-17SA:PS-CV-1:BCKPLN', 'SI-17SA:PS-CV-2:BCKPLN',
            'SI-17M1:PS-CH:BCKPLN', 'SI-17M1:PS-CV:BCKPLN',
            'SI-17M2:PS-CH:BCKPLN', 'SI-17M2:PS-CV:BCKPLN',
            'SI-17C1:PS-CH:BCKPLN', 'SI-17C1:PS-CV:BCKPLN',
            'SI-17C2:PS-CH:BCKPLN', 'SI-17C2:PS-CV-1:BCKPLN',
            'SI-17C2:PS-CV-2:BCKPLN',
            'SI-17C3:PS-CH:BCKPLN', 'SI-17C3:PS-CV-1:BCKPLN',
            'SI-17C3:PS-CV-2:BCKPLN',
            'SI-17C4:PS-CH:BCKPLN', 'SI-17C4:PS-CV:BCKPLN',

            'SI-18M1:PS-CH:BCKPLN', 'SI-18M1:PS-CV:BCKPLN',
            'SI-18M2:PS-CH:BCKPLN', 'SI-18M2:PS-CV:BCKPLN',
            'SI-18C1:PS-CH:BCKPLN', 'SI-18C1:PS-CV:BCKPLN',
            'SI-18C2:PS-CH:BCKPLN', 'SI-18C2:PS-CV-1:BCKPLN',
            'SI-18C2:PS-CV-2:BCKPLN',
            'SI-18C3:PS-CH:BCKPLN', 'SI-18C3:PS-CV-1:BCKPLN',
            'SI-18C3:PS-CV-2:BCKPLN',
            'SI-18C4:PS-CH:BCKPLN', 'SI-18C4:PS-CV:BCKPLN',

            'SI-19M1:PS-CH:BCKPLN', 'SI-19M1:PS-CV:BCKPLN',
            'SI-19M2:PS-CH:BCKPLN', 'SI-19M2:PS-CV:BCKPLN',
            'SI-19C1:PS-CH:BCKPLN', 'SI-19C1:PS-CV:BCKPLN',
            'SI-19C2:PS-CH:BCKPLN', 'SI-19C2:PS-CV-1:BCKPLN',
            'SI-19C2:PS-CV-2:BCKPLN',
            'SI-19C3:PS-CH:BCKPLN', 'SI-19C3:PS-CV-1:BCKPLN',
            'SI-19C3:PS-CV-2:BCKPLN',
            'SI-19C4:PS-CH:BCKPLN', 'SI-19C4:PS-CV:BCKPLN',

            'SI-20M1:PS-CH:BCKPLN', 'SI-20M1:PS-CV:BCKPLN',
            'SI-20M2:PS-CH:BCKPLN', 'SI-20M2:PS-CV:BCKPLN',
            'SI-20C1:PS-CH:BCKPLN', 'SI-20C1:PS-CV:BCKPLN',
            'SI-20C2:PS-CH:BCKPLN', 'SI-20C2:PS-CV-1:BCKPLN',
            'SI-20C2:PS-CV-2:BCKPLN',
            'SI-20C3:PS-CH:BCKPLN', 'SI-20C3:PS-CV-1:BCKPLN',
            'SI-20C3:PS-CV-2:BCKPLN',
            'SI-20C4:PS-CH:BCKPLN', 'SI-20C4:PS-CV:BCKPLN',
            ),
        },
    'SI-Glob:TI-Mags-Quads': {
        'database': {
            'Src': {'enums': ('TunSI', 'Cycle')},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 3920},
            'Duration': {'value': 2000},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'SI-Fam:PS-QDA:BCKPLN',
            'SI-Fam:PS-QFA:BCKPLN',

            'SI-Fam:PS-QDB1:BCKPLN',
            'SI-Fam:PS-QDB2:BCKPLN',
            'SI-Fam:PS-QFB:BCKPLN',

            'SI-Fam:PS-QDP1:BCKPLN',
            'SI-Fam:PS-QDP2:BCKPLN',
            'SI-Fam:PS-QFP:BCKPLN',

            'SI-Fam:PS-Q1:BCKPLN',
            'SI-Fam:PS-Q2:BCKPLN',
            'SI-Fam:PS-Q3:BCKPLN',
            'SI-Fam:PS-Q4:BCKPLN',

            # 'SI-Fam:PS-QB1:BCKPLN',
            # 'SI-Fam:PS-QB2:BCKPLN',
            ),
        },
    'SI-Glob:TI-Mags-QTrims': {
        'database': {
            'Src': {'enums': ('TunSI', 'Cycle')},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 3920},
            'Duration': {'value': 2000},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'SI-01C1:PS-Q1:BCKPLN', 'SI-01C1:PS-Q2:BCKPLN',
            'SI-01C2:PS-Q3:BCKPLN', 'SI-01C2:PS-Q4:BCKPLN',
            'SI-01C3:PS-Q4:BCKPLN', 'SI-01C3:PS-Q3:BCKPLN',
            'SI-01C4:PS-Q2:BCKPLN', 'SI-01C4:PS-Q1:BCKPLN',
            'SI-01M1:PS-QFA:BCKPLN', 'SI-01M1:PS-QDA:BCKPLN',
            'SI-01M2:PS-QFA:BCKPLN', 'SI-01M2:PS-QDA:BCKPLN',

            'SI-02C1:PS-Q1:BCKPLN', 'SI-02C1:PS-Q2:BCKPLN',
            'SI-02C2:PS-Q3:BCKPLN', 'SI-02C2:PS-Q4:BCKPLN',
            'SI-02C3:PS-Q4:BCKPLN', 'SI-02C3:PS-Q3:BCKPLN',
            'SI-02C4:PS-Q2:BCKPLN', 'SI-02C4:PS-Q1:BCKPLN',
            'SI-02M1:PS-QFB:BCKPLN', 'SI-02M1:PS-QDB1:BCKPLN',
            'SI-02M1:PS-QDB2:BCKPLN', 'SI-02M2:PS-QFB:BCKPLN',
            'SI-02M2:PS-QDB1:BCKPLN', 'SI-02M2:PS-QDB2:BCKPLN',

            'SI-03C1:PS-Q1:BCKPLN', 'SI-03C1:PS-Q2:BCKPLN',
            'SI-03C2:PS-Q3:BCKPLN', 'SI-03C2:PS-Q4:BCKPLN',
            'SI-03C3:PS-Q4:BCKPLN', 'SI-03C3:PS-Q3:BCKPLN',
            'SI-03C4:PS-Q2:BCKPLN', 'SI-03C4:PS-Q1:BCKPLN',
            'SI-03M1:PS-QFP:BCKPLN', 'SI-03M1:PS-QDP1:BCKPLN',
            'SI-03M1:PS-QDP2:BCKPLN',
            'SI-03M2:PS-QFP:BCKPLN', 'SI-03M2:PS-QDP1:BCKPLN',
            'SI-03M2:PS-QDP2:BCKPLN',

            'SI-04C1:PS-Q1:BCKPLN', 'SI-04C1:PS-Q2:BCKPLN',
            'SI-04C2:PS-Q3:BCKPLN', 'SI-04C2:PS-Q4:BCKPLN',
            'SI-04C3:PS-Q4:BCKPLN', 'SI-04C3:PS-Q3:BCKPLN',
            'SI-04C4:PS-Q2:BCKPLN', 'SI-04C4:PS-Q1:BCKPLN',
            'SI-04M1:PS-QFB:BCKPLN', 'SI-04M1:PS-QDB1:BCKPLN',
            'SI-04M1:PS-QDB2:BCKPLN', 'SI-04M2:PS-QFB:BCKPLN',
            'SI-04M2:PS-QDB1:BCKPLN', 'SI-04M2:PS-QDB2:BCKPLN',

            'SI-05C1:PS-Q1:BCKPLN', 'SI-05C1:PS-Q2:BCKPLN',
            'SI-05C2:PS-Q3:BCKPLN', 'SI-05C2:PS-Q4:BCKPLN',
            'SI-05C3:PS-Q4:BCKPLN', 'SI-05C3:PS-Q3:BCKPLN',
            'SI-05C4:PS-Q2:BCKPLN', 'SI-05C4:PS-Q1:BCKPLN',
            'SI-05M1:PS-QFA:BCKPLN', 'SI-05M1:PS-QDA:BCKPLN',
            'SI-05M2:PS-QFA:BCKPLN', 'SI-05M2:PS-QDA:BCKPLN',

            'SI-06C1:PS-Q1:BCKPLN', 'SI-06C1:PS-Q2:BCKPLN',
            'SI-06C2:PS-Q3:BCKPLN', 'SI-06C2:PS-Q4:BCKPLN',
            'SI-06C3:PS-Q4:BCKPLN', 'SI-06C3:PS-Q3:BCKPLN',
            'SI-06C4:PS-Q2:BCKPLN', 'SI-06C4:PS-Q1:BCKPLN',
            'SI-06M1:PS-QFB:BCKPLN', 'SI-06M1:PS-QDB1:BCKPLN',
            'SI-06M1:PS-QDB2:BCKPLN',
            'SI-06M2:PS-QFB:BCKPLN', 'SI-06M2:PS-QDB1:BCKPLN',
            'SI-06M2:PS-QDB2:BCKPLN',

            'SI-07C1:PS-Q1:BCKPLN', 'SI-07C1:PS-Q2:BCKPLN',
            'SI-07C2:PS-Q3:BCKPLN', 'SI-07C2:PS-Q4:BCKPLN',
            'SI-07C3:PS-Q4:BCKPLN', 'SI-07C3:PS-Q3:BCKPLN',
            'SI-07C4:PS-Q2:BCKPLN', 'SI-07C4:PS-Q1:BCKPLN',
            'SI-07M1:PS-QFP:BCKPLN', 'SI-07M1:PS-QDP1:BCKPLN',
            'SI-07M1:PS-QDP2:BCKPLN',
            'SI-07M2:PS-QFP:BCKPLN', 'SI-07M2:PS-QDP1:BCKPLN',
            'SI-07M2:PS-QDP2:BCKPLN',

            'SI-08C1:PS-Q1:BCKPLN', 'SI-08C1:PS-Q2:BCKPLN',
            'SI-08C2:PS-Q3:BCKPLN', 'SI-08C2:PS-Q4:BCKPLN',
            'SI-08C3:PS-Q4:BCKPLN', 'SI-08C3:PS-Q3:BCKPLN',
            'SI-08C4:PS-Q2:BCKPLN', 'SI-08C4:PS-Q1:BCKPLN',
            'SI-08M1:PS-QFB:BCKPLN', 'SI-08M1:PS-QDB1:BCKPLN',
            'SI-08M1:PS-QDB2:BCKPLN',
            'SI-08M2:PS-QFB:BCKPLN', 'SI-08M2:PS-QDB1:BCKPLN',
            'SI-08M2:PS-QDB2:BCKPLN',

            'SI-09C1:PS-Q1:BCKPLN', 'SI-09C1:PS-Q2:BCKPLN',
            'SI-09C2:PS-Q3:BCKPLN', 'SI-09C2:PS-Q4:BCKPLN',
            'SI-09C3:PS-Q4:BCKPLN', 'SI-09C3:PS-Q3:BCKPLN',
            'SI-09C4:PS-Q2:BCKPLN', 'SI-09C4:PS-Q1:BCKPLN',
            'SI-09M1:PS-QFA:BCKPLN', 'SI-09M1:PS-QDA:BCKPLN',
            'SI-09M2:PS-QFA:BCKPLN', 'SI-09M2:PS-QDA:BCKPLN',

            'SI-10C1:PS-Q1:BCKPLN', 'SI-10C1:PS-Q2:BCKPLN',
            'SI-10C2:PS-Q3:BCKPLN', 'SI-10C2:PS-Q4:BCKPLN',
            'SI-10C3:PS-Q4:BCKPLN', 'SI-10C3:PS-Q3:BCKPLN',
            'SI-10C4:PS-Q2:BCKPLN', 'SI-10C4:PS-Q1:BCKPLN',
            'SI-10M1:PS-QFB:BCKPLN', 'SI-10M1:PS-QDB1:BCKPLN',
            'SI-10M1:PS-QDB2:BCKPLN', 'SI-10M2:PS-QFB:BCKPLN',
            'SI-10M2:PS-QDB1:BCKPLN', 'SI-10M2:PS-QDB2:BCKPLN',

            'SI-11C1:PS-Q1:BCKPLN', 'SI-11C1:PS-Q2:BCKPLN',
            'SI-11C2:PS-Q3:BCKPLN', 'SI-11C2:PS-Q4:BCKPLN',
            'SI-11C3:PS-Q4:BCKPLN', 'SI-11C3:PS-Q3:BCKPLN',
            'SI-11C4:PS-Q2:BCKPLN', 'SI-11C4:PS-Q1:BCKPLN',
            'SI-11M1:PS-QFP:BCKPLN', 'SI-11M1:PS-QDP1:BCKPLN',
            'SI-11M1:PS-QDP2:BCKPLN',
            'SI-11M2:PS-QFP:BCKPLN', 'SI-11M2:PS-QDP1:BCKPLN',
            'SI-11M2:PS-QDP2:BCKPLN',

            'SI-12C1:PS-Q1:BCKPLN', 'SI-12C1:PS-Q2:BCKPLN',
            'SI-12C2:PS-Q3:BCKPLN', 'SI-12C2:PS-Q4:BCKPLN',
            'SI-12C3:PS-Q4:BCKPLN', 'SI-12C3:PS-Q3:BCKPLN',
            'SI-12C4:PS-Q2:BCKPLN', 'SI-12C4:PS-Q1:BCKPLN',
            'SI-12M1:PS-QFB:BCKPLN', 'SI-12M1:PS-QDB1:BCKPLN',
            'SI-12M1:PS-QDB2:BCKPLN',
            'SI-12M2:PS-QFB:BCKPLN', 'SI-12M2:PS-QDB1:BCKPLN',
            'SI-12M2:PS-QDB2:BCKPLN',

            'SI-13C1:PS-Q1:BCKPLN', 'SI-13C1:PS-Q2:BCKPLN',
            'SI-13C2:PS-Q3:BCKPLN', 'SI-13C2:PS-Q4:BCKPLN',
            'SI-13C3:PS-Q4:BCKPLN', 'SI-13C3:PS-Q3:BCKPLN',
            'SI-13C4:PS-Q2:BCKPLN', 'SI-13C4:PS-Q1:BCKPLN',
            'SI-13M1:PS-QFA:BCKPLN', 'SI-13M1:PS-QDA:BCKPLN',
            'SI-13M2:PS-QFA:BCKPLN', 'SI-13M2:PS-QDA:BCKPLN',

            'SI-14C1:PS-Q1:BCKPLN', 'SI-14C1:PS-Q2:BCKPLN',
            'SI-14C2:PS-Q3:BCKPLN', 'SI-14C2:PS-Q4:BCKPLN',
            'SI-14C3:PS-Q4:BCKPLN', 'SI-14C3:PS-Q3:BCKPLN',
            'SI-14C4:PS-Q2:BCKPLN', 'SI-14C4:PS-Q1:BCKPLN',
            'SI-14M1:PS-QFB:BCKPLN', 'SI-14M1:PS-QDB1:BCKPLN',
            'SI-14M1:PS-QDB2:BCKPLN',
            'SI-14M2:PS-QFB:BCKPLN', 'SI-14M2:PS-QDB1:BCKPLN',
            'SI-14M2:PS-QDB2:BCKPLN',

            'SI-15C1:PS-Q1:BCKPLN', 'SI-15C1:PS-Q2:BCKPLN',
            'SI-15C2:PS-Q3:BCKPLN', 'SI-15C2:PS-Q4:BCKPLN',
            'SI-15C3:PS-Q4:BCKPLN', 'SI-15C3:PS-Q3:BCKPLN',
            'SI-15C4:PS-Q2:BCKPLN', 'SI-15C4:PS-Q1:BCKPLN',
            'SI-15M1:PS-QFP:BCKPLN', 'SI-15M1:PS-QDP1:BCKPLN',
            'SI-15M1:PS-QDP2:BCKPLN',
            'SI-15M2:PS-QFP:BCKPLN', 'SI-15M2:PS-QDP1:BCKPLN',
            'SI-15M2:PS-QDP2:BCKPLN',

            'SI-16C1:PS-Q1:BCKPLN', 'SI-16C1:PS-Q2:BCKPLN',
            'SI-16C2:PS-Q3:BCKPLN', 'SI-16C2:PS-Q4:BCKPLN',
            'SI-16C3:PS-Q4:BCKPLN', 'SI-16C3:PS-Q3:BCKPLN',
            'SI-16C4:PS-Q2:BCKPLN', 'SI-16C4:PS-Q1:BCKPLN',
            'SI-16M1:PS-QFB:BCKPLN', 'SI-16M1:PS-QDB1:BCKPLN',
            'SI-16M1:PS-QDB2:BCKPLN',
            'SI-16M2:PS-QFB:BCKPLN', 'SI-16M2:PS-QDB1:BCKPLN',
            'SI-16M2:PS-QDB2:BCKPLN',

            'SI-17C1:PS-Q1:BCKPLN', 'SI-17C1:PS-Q2:BCKPLN',
            'SI-17C2:PS-Q3:BCKPLN', 'SI-17C2:PS-Q4:BCKPLN',
            'SI-17C3:PS-Q4:BCKPLN', 'SI-17C3:PS-Q3:BCKPLN',
            'SI-17C4:PS-Q2:BCKPLN', 'SI-17C4:PS-Q1:BCKPLN',
            'SI-17M1:PS-QFA:BCKPLN', 'SI-17M1:PS-QDA:BCKPLN',
            'SI-17M2:PS-QFA:BCKPLN', 'SI-17M2:PS-QDA:BCKPLN',

            'SI-18C1:PS-Q1:BCKPLN', 'SI-18C1:PS-Q2:BCKPLN',
            'SI-18C2:PS-Q3:BCKPLN', 'SI-18C2:PS-Q4:BCKPLN',
            'SI-18C3:PS-Q4:BCKPLN', 'SI-18C3:PS-Q3:BCKPLN',
            'SI-18C4:PS-Q2:BCKPLN', 'SI-18C4:PS-Q1:BCKPLN',
            'SI-18M1:PS-QFB:BCKPLN', 'SI-18M1:PS-QDB1:BCKPLN',
            'SI-18M1:PS-QDB2:BCKPLN',
            'SI-18M2:PS-QFB:BCKPLN', 'SI-18M2:PS-QDB1:BCKPLN',
            'SI-18M2:PS-QDB2:BCKPLN',

            'SI-19C1:PS-Q1:BCKPLN', 'SI-19C1:PS-Q2:BCKPLN',
            'SI-19C2:PS-Q3:BCKPLN', 'SI-19C2:PS-Q4:BCKPLN',
            'SI-19C3:PS-Q4:BCKPLN', 'SI-19C3:PS-Q3:BCKPLN',
            'SI-19C4:PS-Q2:BCKPLN', 'SI-19C4:PS-Q1:BCKPLN',
            'SI-19M1:PS-QFP:BCKPLN', 'SI-19M1:PS-QDP1:BCKPLN',
            'SI-19M1:PS-QDP2:BCKPLN',
            'SI-19M2:PS-QFP:BCKPLN', 'SI-19M2:PS-QDP1:BCKPLN',
            'SI-19M2:PS-QDP2:BCKPLN',

            'SI-20C1:PS-Q1:BCKPLN', 'SI-20C1:PS-Q2:BCKPLN',
            'SI-20C2:PS-Q3:BCKPLN', 'SI-20C2:PS-Q4:BCKPLN',
            'SI-20C3:PS-Q4:BCKPLN', 'SI-20C3:PS-Q3:BCKPLN',
            'SI-20C4:PS-Q2:BCKPLN', 'SI-20C4:PS-Q1:BCKPLN',
            'SI-20M1:PS-QFB:BCKPLN', 'SI-20M1:PS-QDB1:BCKPLN',
            'SI-20M1:PS-QDB2:BCKPLN',
            'SI-20M2:PS-QFB:BCKPLN', 'SI-20M2:PS-QDB1:BCKPLN',
            'SI-20M2:PS-QDB2:BCKPLN',
            ),
        },
    'SI-Glob:TI-Mags-Skews': {
        'database': {
            'Src': {'enums': ('CplSI', 'Cycle')},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 3920},
            'Duration': {'value': 2000},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'SI-01M1:PS-QS:BCKPLN',
            'SI-01M2:PS-QS:BCKPLN',
            'SI-01C1:PS-QS:BCKPLN',
            'SI-01C2:PS-QS:BCKPLN',
            'SI-01C3:PS-QS:BCKPLN',

            'SI-02M1:PS-QS:BCKPLN',
            'SI-02M2:PS-QS:BCKPLN',
            'SI-02C1:PS-QS:BCKPLN',
            'SI-02C2:PS-QS:BCKPLN',
            'SI-02C3:PS-QS:BCKPLN',

            'SI-03M1:PS-QS:BCKPLN',
            'SI-03M2:PS-QS:BCKPLN',
            'SI-03C1:PS-QS:BCKPLN',
            'SI-03C2:PS-QS:BCKPLN',
            'SI-03C3:PS-QS:BCKPLN',

            'SI-04M1:PS-QS:BCKPLN',
            'SI-04M2:PS-QS:BCKPLN',
            'SI-04C1:PS-QS:BCKPLN',
            'SI-04C2:PS-QS:BCKPLN',
            'SI-04C3:PS-QS:BCKPLN',

            'SI-05M1:PS-QS:BCKPLN',
            'SI-05M2:PS-QS:BCKPLN',
            'SI-05C1:PS-QS:BCKPLN',
            'SI-05C2:PS-QS:BCKPLN',
            'SI-05C3:PS-QS:BCKPLN',

            'SI-06M1:PS-QS:BCKPLN',
            'SI-06M2:PS-QS:BCKPLN',
            'SI-06C1:PS-QS:BCKPLN',
            'SI-06C2:PS-QS:BCKPLN',
            'SI-06C3:PS-QS:BCKPLN',

            'SI-07M1:PS-QS:BCKPLN',
            'SI-07M2:PS-QS:BCKPLN',
            'SI-07C1:PS-QS:BCKPLN',
            'SI-07C2:PS-QS:BCKPLN',
            'SI-07C3:PS-QS:BCKPLN',

            'SI-08M1:PS-QS:BCKPLN',
            'SI-08M2:PS-QS:BCKPLN',
            'SI-08C1:PS-QS:BCKPLN',
            'SI-08C2:PS-QS:BCKPLN',
            'SI-08C3:PS-QS:BCKPLN',

            'SI-09M1:PS-QS:BCKPLN',
            'SI-09M2:PS-QS:BCKPLN',
            'SI-09C1:PS-QS:BCKPLN',
            'SI-09C2:PS-QS:BCKPLN',
            'SI-09C3:PS-QS:BCKPLN',

            'SI-10SB:PS-QS-1:BCKPLN',
            'SI-10SB:PS-QS-2:BCKPLN',
            'SI-10M1:PS-QS:BCKPLN',
            'SI-10M2:PS-QS:BCKPLN',
            'SI-10C1:PS-QS:BCKPLN',
            'SI-10C2:PS-QS:BCKPLN',
            'SI-10C3:PS-QS:BCKPLN',

            'SI-11M1:PS-QS:BCKPLN',
            'SI-11M2:PS-QS:BCKPLN',
            'SI-11C1:PS-QS:BCKPLN',
            'SI-11C2:PS-QS:BCKPLN',
            'SI-11C3:PS-QS:BCKPLN',

            'SI-12M1:PS-QS:BCKPLN',
            'SI-12M2:PS-QS:BCKPLN',
            'SI-12C1:PS-QS:BCKPLN',
            'SI-12C2:PS-QS:BCKPLN',
            'SI-12C3:PS-QS:BCKPLN',

            'SI-13M1:PS-QS:BCKPLN',
            'SI-13M2:PS-QS:BCKPLN',
            'SI-13C1:PS-QS:BCKPLN',
            'SI-13C2:PS-QS:BCKPLN',
            'SI-13C3:PS-QS:BCKPLN',

            'SI-14M1:PS-QS:BCKPLN',
            'SI-14M2:PS-QS:BCKPLN',
            'SI-14C1:PS-QS:BCKPLN',
            'SI-14C2:PS-QS:BCKPLN',
            'SI-14C3:PS-QS:BCKPLN',

            'SI-15M1:PS-QS:BCKPLN',
            'SI-15M2:PS-QS:BCKPLN',
            'SI-15C1:PS-QS:BCKPLN',
            'SI-15C2:PS-QS:BCKPLN',
            'SI-15C3:PS-QS:BCKPLN',

            'SI-16M1:PS-QS:BCKPLN',
            'SI-16M2:PS-QS:BCKPLN',
            'SI-16C1:PS-QS:BCKPLN',
            'SI-16C2:PS-QS:BCKPLN',
            'SI-16C3:PS-QS:BCKPLN',

            'SI-17M1:PS-QS:BCKPLN',
            'SI-17M2:PS-QS:BCKPLN',
            'SI-17C1:PS-QS:BCKPLN',
            'SI-17C2:PS-QS:BCKPLN',
            'SI-17C3:PS-QS:BCKPLN',

            'SI-18M1:PS-QS:BCKPLN',
            'SI-18M2:PS-QS:BCKPLN',
            'SI-18C1:PS-QS:BCKPLN',
            'SI-18C2:PS-QS:BCKPLN',
            'SI-18C3:PS-QS:BCKPLN',

            'SI-19M1:PS-QS:BCKPLN',
            'SI-19M2:PS-QS:BCKPLN',
            'SI-19C1:PS-QS:BCKPLN',
            'SI-19C2:PS-QS:BCKPLN',
            'SI-19C3:PS-QS:BCKPLN',

            'SI-20M1:PS-QS:BCKPLN',
            'SI-20M2:PS-QS:BCKPLN',
            'SI-20C1:PS-QS:BCKPLN',
            'SI-20C2:PS-QS:BCKPLN',
            'SI-20C3:PS-QS:BCKPLN',
            ),
        },
    'SI-Glob:TI-Mags-Bends': {
        'database': {
            'Src': {'enums': ('Cycle', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 3920},
            'Duration': {'value': 2000},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (0, 1)},
            },
        'channels': (
            'SI-Fam:PS-B1B2-1:BCKPLN',
            # trigger reaches this PS by cascating:
            # 'SI-Fam:PS-B1B2-2:BCKPLN',
            ),
        },
    'SI-Glob:TI-Mags-Sexts': {
        'database': {
            'Src': {'enums': ('Cycle', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 3920},
            'Duration': {'value': 2000},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'SI-Fam:PS-SFA0:BCKPLN', 'SI-Fam:PS-SFA1:BCKPLN',
            'SI-Fam:PS-SFA2:BCKPLN',
            'SI-Fam:PS-SDA0:BCKPLN', 'SI-Fam:PS-SDA1:BCKPLN',
            'SI-Fam:PS-SDA2:BCKPLN', 'SI-Fam:PS-SDA3:BCKPLN',
            'SI-Fam:PS-SFB0:BCKPLN', 'SI-Fam:PS-SFB1:BCKPLN',
            'SI-Fam:PS-SFB2:BCKPLN',
            'SI-Fam:PS-SDB0:BCKPLN', 'SI-Fam:PS-SDB1:BCKPLN',
            'SI-Fam:PS-SDB2:BCKPLN', 'SI-Fam:PS-SDB3:BCKPLN',
            'SI-Fam:PS-SFP0:BCKPLN', 'SI-Fam:PS-SFP1:BCKPLN',
            'SI-Fam:PS-SFP2:BCKPLN',
            'SI-Fam:PS-SDP0:BCKPLN', 'SI-Fam:PS-SDP1:BCKPLN',
            'SI-Fam:PS-SDP2:BCKPLN', 'SI-Fam:PS-SDP3:BCKPLN',
            ),
        },
    'SI-01:TI-Mags-FFCorrs': {
        'database': {
            'Src': {'enums': ('Cycle', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 3920},
            'Duration': {'value': 2000},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (0, 1)},
        },
        'channels': (
            'SI-01M1:PS-FFCH:BCKPLN', 'SI-01M1:PS-FFCV:BCKPLN',
            'SI-01M2:PS-FFCH:BCKPLN', 'SI-01M2:PS-FFCV:BCKPLN',
        ),
    },
    'BO-Glob:TI-Mags-Fams': {
        'database': {
            'Src': {'enums': ('Cycle', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 3920},
            'Duration': {'value': 490000},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'BO-Fam:PS-B-1:BCKPLN', 'BO-Fam:PS-B-2:BCKPLN',
            'BO-Fam:PS-QF:BCKPLN', 'BO-Fam:PS-QD:BCKPLN',
            'BO-Fam:PS-SF:BCKPLN', 'BO-Fam:PS-SD:BCKPLN',
            ),
        },
    'BO-Glob:TI-Mags-Corrs': {
        'database': {
            'Src': {'enums': ('Cycle', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'BO-01U:PS-CH:BCKPLN', 'BO-01U:PS-CV:BCKPLN',
            'BO-02D:PS-QS:BCKPLN',
            'BO-03U:PS-CH:BCKPLN', 'BO-03U:PS-CV:BCKPLN',
            'BO-05U:PS-CH:BCKPLN', 'BO-05U:PS-CV:BCKPLN',
            'BO-07U:PS-CH:BCKPLN', 'BO-07U:PS-CV:BCKPLN',
            'BO-09U:PS-CH:BCKPLN', 'BO-09U:PS-CV:BCKPLN',
            'BO-11U:PS-CH:BCKPLN', 'BO-11U:PS-CV:BCKPLN',
            'BO-13U:PS-CH:BCKPLN', 'BO-13U:PS-CV:BCKPLN',
            'BO-15U:PS-CH:BCKPLN', 'BO-15U:PS-CV:BCKPLN',
            'BO-17U:PS-CH:BCKPLN', 'BO-17U:PS-CV:BCKPLN',
            'BO-19U:PS-CH:BCKPLN', 'BO-19U:PS-CV:BCKPLN',
            'BO-21U:PS-CH:BCKPLN', 'BO-21U:PS-CV:BCKPLN',
            'BO-23U:PS-CH:BCKPLN', 'BO-23U:PS-CV:BCKPLN',
            'BO-25U:PS-CH:BCKPLN', 'BO-25U:PS-CV:BCKPLN',
            'BO-27U:PS-CH:BCKPLN', 'BO-27U:PS-CV:BCKPLN',
            'BO-29U:PS-CH:BCKPLN', 'BO-29U:PS-CV:BCKPLN',
            'BO-31U:PS-CH:BCKPLN', 'BO-31U:PS-CV:BCKPLN',
            'BO-33U:PS-CH:BCKPLN', 'BO-33U:PS-CV:BCKPLN',
            'BO-35U:PS-CH:BCKPLN', 'BO-35U:PS-CV:BCKPLN',
            'BO-37U:PS-CH:BCKPLN', 'BO-37U:PS-CV:BCKPLN',
            'BO-39U:PS-CH:BCKPLN', 'BO-39U:PS-CV:BCKPLN',
            'BO-41U:PS-CH:BCKPLN', 'BO-41U:PS-CV:BCKPLN',
            'BO-43U:PS-CH:BCKPLN', 'BO-43U:PS-CV:BCKPLN',
            'BO-45U:PS-CH:BCKPLN', 'BO-45U:PS-CV:BCKPLN',
            'BO-47U:PS-CH:BCKPLN', 'BO-47U:PS-CV:BCKPLN',
            'BO-49D:PS-CH:BCKPLN', 'BO-49U:PS-CV:BCKPLN',
            ),
        },
    'TB-Glob:TI-Mags': {
        'database': {
            'Src': {'enums': ('Cycle', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 3920},
            'Duration': {'value': 490000},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (0, 1)},
            },
        'channels': (
            'TB-01:PS-CV-1:BCKPLN', 'TB-01:PS-CH-1:BCKPLN',
            'TB-01:PS-CV-2:BCKPLN', 'TB-01:PS-CH-2:BCKPLN',
            'TB-02:PS-CV-1:BCKPLN', 'TB-02:PS-CH-1:BCKPLN',
            'TB-02:PS-CV-2:BCKPLN', 'TB-02:PS-CH-2:BCKPLN',
            'TB-04:PS-CV-1:BCKPLN', 'TB-04:PS-CH-1:BCKPLN',
            'TB-04:PS-CV-2:BCKPLN', 'TB-04:PS-CH-2:BCKPLN',
            'TB-01:PS-QD1:BCKPLN', 'TB-01:PS-QF1:BCKPLN',
            'TB-02:PS-QD2A:BCKPLN', 'TB-02:PS-QD2B:BCKPLN',
            'TB-02:PS-QF2A:BCKPLN', 'TB-02:PS-QF2B:BCKPLN',
            'TB-03:PS-QD3:BCKPLN', 'TB-03:PS-QF3:BCKPLN',
            'TB-04:PS-QD4:BCKPLN', 'TB-04:PS-QF4:BCKPLN',
            'TB-Fam:PS-B:BCKPLN',
            ),
        },
    'TS-Glob:TI-Mags': {
        'database': {
            'Src': {'enums': ('Cycle', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 3920},
            'Duration': {'value': 490000},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (0, 1)},
            },
        'channels': (
             'TS-01:PS-CV-1:BCKPLN', 'TS-01:PS-CH:BCKPLN',
             'TS-01:PS-CV-2:BCKPLN',
             'TS-02:PS-CV:BCKPLN', 'TS-02:PS-CH:BCKPLN',
             'TS-03:PS-CV:BCKPLN', 'TS-03:PS-CH:BCKPLN',
             'TS-04:PS-CV-1:BCKPLN', 'TS-04:PS-CH:BCKPLN',
             'TS-04:PS-CV-2:BCKPLN',
             'TS-01:PS-QF1A:BCKPLN', 'TS-01:PS-QF1B:BCKPLN',
             'TS-02:PS-QD2:BCKPLN', 'TS-02:PS-QF2:BCKPLN',
             'TS-03:PS-QF3:BCKPLN',
             'TS-04:PS-QD4A:BCKPLN', 'TS-04:PS-QD4B:BCKPLN',
             'TS-04:PS-QF4:BCKPLN',
             'TS-Fam:PS-B:BCKPLN',
            ),
        },
    # ### Linac ###
    'LI-01:TI-EGun-MultBun': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 0.3, 'hilim': 1.6},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 2)},
            },
        'channels': ('LI-01:EG-EGun:MULTIPULSEAMPLIFIER', ),
        },
    'LI-01:TI-EGun-MultBunPre': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 6.8, 'hilim': 20.0},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 2)},
            },
        'channels': ('LI-01:EG-EGun:MULTIPRETRIGGERAMPLIFIER', ),
        },
    'LI-01:TI-EGun-SglBun': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 0.3, 'hilim': 1.6},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (0, 2)},
            },
        'channels': ('LI-01:EG-EGun:SINGLEPULSEAMPLIFIER', ),
        },
    'LI-01:TI-Modltr-1': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 0, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 3, 'hilim': 100},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('LI-RaMD01:MD-PPS:TRIGIN', ),
        },
    'LI-01:TI-Modltr-2': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 3, 'hilim': 100},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('LI-RaMD02:MD-PPS:TRIGIN', ),
        },
    'LI-Glob:TI-SSAmp-SHB': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 3, 'hilim': 100},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('LI-RaRF02:RF-SSAmp-1:TRIG500MHZ', ),
        },
    'LI-Glob:TI-SSAmp-Kly1': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 3, 'hilim': 100},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('LI-RaRF02:RF-SSAmp-2:TRIG3GHZ', ),
        },
    'LI-Glob:TI-SSAmp-Kly2': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 3, 'hilim': 100},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('LI-RaRF02:RF-SSAmp-3:TRIG3GHZ', ),
        },
    'LI-Glob:TI-LLRF-SHB': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 3, 'hilim': 100},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('LI-RaRF01:RF-LLRFProc:TRIG1', ),
        },
    'LI-Glob:TI-LLRF-Kly1': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 3, 'hilim': 100},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('LI-RaRF01:RF-LLRFProc:TRIG2', ),
        },
    'LI-Glob:TI-LLRF-Kly2': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 3, 'hilim': 100},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('LI-RaRF01:RF-LLRFProc:TRIG3', ),
        },
    # Pulsed Magnets
    'TB-04:TI-InjSept': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 3, 'hilim': 100},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},  # EVR-OTP port
            },
        'channels': ('TB-04:PU-InjSeptCtrl:TRIGIN', ),
        },
    'BO-01D:TI-InjKckr': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},  # EVR-OTP port
            },
        'channels': ('BO-01D:PU-InjKckrCtrl:TRIGIN', ),
        },
    'AS-Glob:TI-Osc-InjBO': {  # 10.0.38.74
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},  # EVR-OTP port
            },
        'channels': ('IA-01RaInj01:PU-Osc:CH4', ),
        },
    'AS-Glob:TI-Osc-EjeBO': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 2)},  # EVR-OUT port
            },
        'channels': ('IA-20RaInj03:PU-Osc:CH4', ),
        },
    'AS-Glob:TI-Osc-InjSI': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},  # EVR-OTP port
            },
        'channels': ('IA-01RaInj04:PU-Osc:CH1', ),
        },
    'BO-48D:TI-EjeKckr': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 2)},  # EVR-OUT port
            },
        'channels': ('BO-48D:PU-EjeKckrCtrl:TRIGIN', ),
        },
    'TS-01:TI-EjeSeptF': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 2)},  # EVR-OUT port
            },
        'channels': (
            'TS-01:PU-EjeSeptGCtrl-1:TRIGIN',
            ),
        },
    'TS-01:TI-EjeSeptG': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 2)},  # EVR-OUT port
            },
        'channels': (
            'TS-01:PU-EjeSeptGCtrl-2:TRIGIN',
            ),
        },
    'TS-04:TI-InjSeptG-1': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},  # EVR-OTP port
            },
        'channels': (
            'TS-04:PU-InjSeptGCtrl-1:TRIGIN',
            ),
        },
    'TS-04:TI-InjSeptG-2': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},  # EVR-OTP port
            },
        'channels': (
            'TS-04:PU-InjSeptGCtrl-2:TRIGIN',
            ),
        },
    'TS-04:TI-InjSeptF': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},  # EVR-OTP port
            },
        'channels': ('TS-04:PU-InjSeptFCtrl:TRIGIN', ),
        },
    'SI-01SA:TI-InjDpKckr': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},  # EVR-OTP port
            },
        'channels': ('SI-01SA:PU-InjDpKckrCtrl:TRIGIN', ),
        },
    'SI-01SA:TI-InjNLKckr': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},  # EVR-OTP port
            },
        'channels': (
            'SI-01SA:PU-InjNLKckrCtrl:TRIGIN',
            'SI-01SA:PU-InjNLKckrCtrl-CCoilH:TRIGIN',
            'SI-01SA:PU-InjNLKckrCtrl-CCoilV:TRIGIN',
            ),
        },
    'SI-19C4:TI-PingV': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 30},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},  # EVR-OUT port
            },
        'channels': ('SI-19C4:PU-PingVCtrl:TRIGIN', ),
        },
    'AS-Glob:TI-Osc-InjSI2': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},  # EVR-OTP port
        },
        'channels': ('IA-01RaInj05:PU-Osc:AUXIN', ),
        },
    # ### LLRF ###
    'BO-Glob:TI-LLRF-Rmp': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('RA-RaBO01:RF-DigPatch:RAMP', ),
        },
    'BO-Glob:TI-LLRF-Gen': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('RA-RaBO01:RF-DigPatch:GENERIC', ),
        },
    'BO-Glob:TI-LLRF-PsMtn': {
        'database': {
            'Src': {'enums': ('InjBO', 'PsMtn', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': ('RA-RaBO01:RF-DigPatch:ET', ),
        },
    'SI-Glob:TI-LLRF-Rmp': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': (
            'RA-RaSIA01:RF-DigPatch:RAMP',
            # 'RA-RaSIB01:RF-DigPatch:RAMP',
            ),
        },
    'SI-Glob:TI-LLRF-Gen': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'RA-RaSIA01:RF-DigPatch:GENERIC',
            # 'RA-RaSIB01:RF-DigPatch:GENERIC',
            ),
        },
    'SI-Glob:TI-LLRF-PsMtn': {
        'database': {
            'Src': {'enums': ('InjSI', 'PsMtn')},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'RA-RaSIA01:RF-DigPatch:ET',
            # 'RA-RaSIB01:RF-DigPatch:ET',
            ),
        },
    # #### DIAGNOSTICS ######
    'LI-Fam:TI-BPM': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'LI-RaDiag02:TI-TrigFout:TRIGINI',
            'LA-BIH01RACK2:DI-Osc-2:TRIGIN',
            ),
        },
    'LI-Fam:TI-Scrn': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 1000},
            'Duration': {'value': 150, 'hilim': 500000},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': ('LI-RaDiag02:TI-TrigFout:TRIGINIV', ),
        },
    'LI-Fam:TI-ICT': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': ('LA-BIH01RACK2:DI-Osc-1:TRIGIN', ),
        },
    'LI-01:TI-Osc-Modltr': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('LA-MD:DI-Osc:TRIGIN', ),
        },
    'LI-01:TI-GDev': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('LI-IET01RACK1:DI-GDev:IN', ),
        },
    'AS-Fam:TI-Scrn-TBBO': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 1000},
            'Duration': {'value': 150, 'hilim': 500000},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'TB-01:DI-ScrnCam-1:TRIGIN',
            'TB-01:DI-ScrnCam-2:TRIGIN',
            'TB-02:DI-ScrnCam-1:TRIGIN',
            'TB-02:DI-ScrnCam-2:TRIGIN',
            'TB-03:DI-ScrnCam:TRIGIN',
            'TB-04:DI-ScrnCam:TRIGIN',
            'BO-01D:DI-ScrnCam-1:TRIGIN',
            'BO-01D:DI-ScrnCam-2:TRIGIN',
            'BO-02U:DI-ScrnCam:TRIGIN',
            ),
        },
    'TB-Fam:TI-ICT-Integ': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'TB-02:DI-ICTSigCond:TRIGIN',
            'TB-04:DI-ICTSigCond:TRIGIN',
            ),
        },
    'TB-Fam:TI-ICT-Digit': {
        'database': {
            'Src': {'enums': ('InjBO', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'TB-02:DI-ICTDig:TRIGIN',
            'TB-04:DI-ICTDig:TRIGIN',
            ),
        },
    'BO-50U:TI-VLightCam': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 1000},
            'Duration': {'value': 150, 'hilim': 500000},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': (
            'BO-50U:DI-VLightCam:TRIGIN',
            ),
        },
    'BO-Glob:TI-TuneProc': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': (
            'BO-Glob:DI-TuneProc-H:TRIGIN',
            'BO-Glob:DI-TuneProc-V:TRIGIN',
            ),
        },
    'BO-35D:TI-DCCT': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': ('BO-35D:DI-DCCTDig:TRIGIN', ),
        },
    'BO-RaPSE05:TI-Osc': {
        'database': {
            'Src': {'enums': ('InjBO', 'Cycle')},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (2, 0)},
            },
        'channels': ('PA-RaPSE05:DI-Osc-BO:TIMIN', ),
        },
    'TS-Fam:TI-Scrn': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 1000},
            'Duration': {'value': 150, 'hilim': 500000},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'TS-01:DI-ScrnCam:TRIGIN',
            'TS-02:DI-ScrnCam:TRIGIN',
            'TS-03:DI-ScrnCam:TRIGIN',
            'TS-04:DI-ScrnCam-1:TRIGIN',
            'TS-04:DI-ScrnCam-2:TRIGIN',
            'TS-04:DI-ScrnCam-3:TRIGIN',
            ),
        },
    'TS-Fam:TI-ICT-Integ': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'TS-01:DI-ICTSigCond:TRIGIN',
            'TS-04:DI-ICTSigCond:TRIGIN',
            ),
        },
    'TS-Fam:TI-ICT-Digit': {
        'database': {
            'Src': {'enums': ('InjSI', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'TS-01:DI-ICTDig:TRIGIN',
            'TS-04:DI-ICTDig:TRIGIN',
            ),
        },
    # 'SI-Glob:TI-StrkCam-Trig1': {
    #     'database': {
    #         'Src': {'enums': ()},
    #         'Delay': {'value': 0.0},
    #         'RFDelayType': {'value': 1, 'states': (2, 0)},
    #         'NrPulses': {'value': 1, 'hilim': 2},
    #         'Duration': {'value': 150, 'hilim': 550},
    #         'State': {'value': 0},
    #         'Polarity': {'value': 1, 'states': (1, 0)},
    #         },
    #     'channels': ('BA-01B1RaCtrl:DI-StrkCam:TRIG1', ),
    #     },
    # 'SI-Glob:TI-StrkCam-Trig2': {
    #     'database': {
    #         'Src': {'enums': ()},
    #         'Delay': {'value': 0.0},
    #         'RFDelayType': {'value': 1, 'states': (2, 0)},
    #         'NrPulses': {'value': 1, 'hilim': 2},
    #         'Duration': {'value': 150, 'hilim': 550},
    #         'State': {'value': 0},
    #         'Polarity': {'value': 1, 'states': (1, 0)},
    #         },
    #     'channels': ('BA-01B1RaCtrl:DI-StrkCam:TRIG2', ),
    #     },
    'SI-Glob:TI-BbBProcH-Trig1': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-Glob:DI-BbBProc-H:TRIG1', ),
        },
    'SI-Glob:TI-BbBProcH-Trig2': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-Glob:DI-BbBProc-H:TRIG2', ),
        },
    'SI-Glob:TI-BbBProcV-Trig1': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-Glob:DI-BbBProc-V:TRIG1', ),
        },
    'SI-Glob:TI-BbBProcV-Trig2': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-Glob:DI-BbBProc-V:TRIG2', ),
        },
    'SI-Glob:TI-BbBProcL-Trig1': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-Glob:DI-BbBProc-L:TRIG1', ),
        },
    'SI-Glob:TI-BbBProcL-Trig2': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-Glob:DI-BbBProc-L:TRIG2', ),
        },
    'SI-Glob:TI-BbBProcH-Fid': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-Glob:DI-BbBProc-H:FID', ),
        },
    'SI-Glob:TI-BbBProcV-Fid': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-Glob:DI-BbBProc-V:FID', ),
        },
    'SI-Glob:TI-BbBProcL-Fid': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 2},
            'Duration': {'value': 150, 'hilim': 550},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-Glob:DI-BbBProc-L:FID', ),
        },
    'SI-01C2FE:TI-VLightCam': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1, 'hilim': 1000},
            'Duration': {'value': 150, 'hilim': 50000000},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': (
            'SI-01C2FE:DI-VLightCam:TRIGIN',
            ),
        },
    'SI-13C4:TI-DCCT': {
        'database': {
            'Src': {'enums': ('PsMtn', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-13SA:DI-DCCTDig:TRIGIN', ),
        },
    'SI-14C4:TI-DCCT': {
        'database': {
            'Src': {'enums': ('PsMtn', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('SI-14SB:DI-DCCTDig:TRIGIN', ),
        },
    'AS-Glob:TI-FCT': {
        # This trigger will work for both FCTs, from TB and TS transpor lines.
        # Two triggers must be sent for each injection pulse, the first will
        # serve as trigger for the TB FCT and the other for the TS.
        # The delay and duration must be adjusted accordingly to the time it
        # takes for the beam to pass by them.
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 2},
            'Duration': {'value': 350},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('AS-Glob:DI-FCTDig:CH4', ),
        },
    'AS-Glob:TI-FillPtrnMon': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 1, 'states': (1, 0)},
            },
        'channels': ('AS-Glob:DI-FPMDig:CH4', ),
        },
    'TB-Fam:TI-BPM': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'TB-01:DI-BPM-1:CRT0', 'TB-01:DI-BPM-2:CRT0',
            'TB-02:DI-BPM-1:CRT0', 'TB-02:DI-BPM-2:CRT0',
            'TB-03:DI-BPM:CRT0',
            'TB-04:DI-BPM:CRT0',
            ),
        },
    'TS-Fam:TI-BPM': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'TS-01:DI-BPM:CRT1', 'TS-02:DI-BPM:CRT1',
            'TS-03:DI-BPM:CRT1',
            'TS-04:DI-BPM-1:CRT1', 'TS-04:DI-BPM-2:CRT1',
            ),
        },
    'BO-Fam:TI-BPM': {
        'database': {
            'Src': {'enums': ()},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'BO-01U:DI-BPM:CRT0', 'BO-02U:DI-BPM:CRT0',
            'BO-03U:DI-BPM:CRT0', 'BO-04U:DI-BPM:CRT0',
            'BO-05U:DI-BPM:CRT0', 'BO-06U:DI-BPM:CRT0',
            'BO-07U:DI-BPM:CRT0', 'BO-08U:DI-BPM:CRT0',
            'BO-09U:DI-BPM:CRT0', 'BO-10U:DI-BPM:CRT0',
            'BO-11U:DI-BPM:CRT0', 'BO-12U:DI-BPM:CRT0',
            'BO-13U:DI-BPM:CRT0', 'BO-14U:DI-BPM:CRT0',
            'BO-15U:DI-BPM:CRT0', 'BO-16U:DI-BPM:CRT0',
            'BO-17U:DI-BPM:CRT0', 'BO-18U:DI-BPM:CRT0',
            'BO-19U:DI-BPM:CRT0', 'BO-20U:DI-BPM:CRT0',
            'BO-21U:DI-BPM:CRT0', 'BO-22U:DI-BPM:CRT0',
            'BO-23U:DI-BPM:CRT0', 'BO-24U:DI-BPM:CRT0',
            'BO-25U:DI-BPM:CRT0', 'BO-26U:DI-BPM:CRT0',
            'BO-27U:DI-BPM:CRT0', 'BO-28U:DI-BPM:CRT0',
            'BO-29U:DI-BPM:CRT0', 'BO-30U:DI-BPM:CRT0',
            'BO-31U:DI-BPM:CRT0', 'BO-32U:DI-BPM:CRT0',
            'BO-33U:DI-BPM:CRT0', 'BO-34U:DI-BPM:CRT0',
            'BO-35U:DI-BPM:CRT0', 'BO-36U:DI-BPM:CRT0',
            'BO-37U:DI-BPM:CRT0', 'BO-38U:DI-BPM:CRT0',
            'BO-39U:DI-BPM:CRT0', 'BO-40U:DI-BPM:CRT0',
            'BO-41U:DI-BPM:CRT0', 'BO-42U:DI-BPM:CRT0',
            'BO-43U:DI-BPM:CRT0', 'BO-44U:DI-BPM:CRT0',
            'BO-45U:DI-BPM:CRT0', 'BO-46U:DI-BPM:CRT0',
            'BO-47U:DI-BPM:CRT0', 'BO-48U:DI-BPM:CRT0',
            'BO-49U:DI-BPM:CRT0', 'BO-50U:DI-BPM:CRT0',
            ),
        },
    'SI-Fam:TI-BPM': {
        'database': {
            'Src': {'enums': ('FOFBS', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'SI-01M1:DI-BPM:CRT1', 'SI-01M2:DI-BPM:CRT1',
            'SI-01C1:DI-BPM-1:CRT1', 'SI-01C1:DI-BPM-2:CRT1',
            'SI-01C2:DI-BPM:CRT1', 'SI-01C3:DI-BPM-1:CRT1',
            'SI-01C3:DI-BPM-2:CRT1', 'SI-01C4:DI-BPM:CRT1',

            'SI-02M1:DI-BPM:CRT1', 'SI-02M2:DI-BPM:CRT1',
            'SI-02C1:DI-BPM-1:CRT1', 'SI-02C1:DI-BPM-2:CRT1',
            'SI-02C2:DI-BPM:CRT1', 'SI-02C3:DI-BPM-1:CRT1',
            'SI-02C3:DI-BPM-2:CRT1', 'SI-02C4:DI-BPM:CRT1',

            'SI-03M1:DI-BPM:CRT1', 'SI-03M2:DI-BPM:CRT1',
            'SI-03C1:DI-BPM-1:CRT1', 'SI-03C1:DI-BPM-2:CRT1',
            'SI-03C2:DI-BPM:CRT1', 'SI-03C3:DI-BPM-1:CRT1',
            'SI-03C3:DI-BPM-2:CRT1', 'SI-03C4:DI-BPM:CRT1',

            'SI-04M1:DI-BPM:CRT1', 'SI-04M2:DI-BPM:CRT1',
            'SI-04C1:DI-BPM-1:CRT1', 'SI-04C1:DI-BPM-2:CRT1',
            'SI-04C2:DI-BPM:CRT1', 'SI-04C3:DI-BPM-1:CRT1',
            'SI-04C3:DI-BPM-2:CRT1', 'SI-04C4:DI-BPM:CRT1',

            'SI-05M1:DI-BPM:CRT1', 'SI-05M2:DI-BPM:CRT1',
            'SI-05C1:DI-BPM-1:CRT1', 'SI-05C1:DI-BPM-2:CRT1',
            'SI-05C2:DI-BPM:CRT1', 'SI-05C3:DI-BPM-1:CRT1',
            'SI-05C3:DI-BPM-2:CRT1', 'SI-05C4:DI-BPM:CRT1',

            'SI-06M1:DI-BPM:CRT1', 'SI-06M2:DI-BPM:CRT1',
            'SI-06C1:DI-BPM-1:CRT1', 'SI-06C1:DI-BPM-2:CRT1',
            'SI-06C2:DI-BPM:CRT1', 'SI-06C3:DI-BPM-1:CRT1',
            'SI-06C3:DI-BPM-2:CRT1', 'SI-06C4:DI-BPM:CRT1',

            'SI-07M1:DI-BPM:CRT1', 'SI-07M2:DI-BPM:CRT1',
            'SI-07C1:DI-BPM-1:CRT1', 'SI-07C1:DI-BPM-2:CRT1',
            'SI-07C2:DI-BPM:CRT1', 'SI-07C3:DI-BPM-1:CRT1',
            'SI-07C3:DI-BPM-2:CRT1', 'SI-07C4:DI-BPM:CRT1',

            'SI-08M1:DI-BPM:CRT1', 'SI-08M2:DI-BPM:CRT1',
            'SI-08C1:DI-BPM-1:CRT1', 'SI-08C1:DI-BPM-2:CRT1',
            'SI-08C2:DI-BPM:CRT1', 'SI-08C3:DI-BPM-1:CRT1',
            'SI-08C3:DI-BPM-2:CRT1', 'SI-08C4:DI-BPM:CRT1',

            'SI-09M1:DI-BPM:CRT1', 'SI-09M2:DI-BPM:CRT1',
            'SI-09C1:DI-BPM-1:CRT1', 'SI-09C1:DI-BPM-2:CRT1',
            'SI-09C2:DI-BPM:CRT1', 'SI-09C3:DI-BPM-1:CRT1',
            'SI-09C3:DI-BPM-2:CRT1', 'SI-09C4:DI-BPM:CRT1',

            'SI-10M1:DI-BPM:CRT1', 'SI-10M2:DI-BPM:CRT1',
            'SI-10C1:DI-BPM-1:CRT1', 'SI-10C1:DI-BPM-2:CRT1',
            'SI-10C2:DI-BPM:CRT1', 'SI-10C3:DI-BPM-1:CRT1',
            'SI-10C3:DI-BPM-2:CRT1', 'SI-10C4:DI-BPM:CRT1',

            'SI-11M1:DI-BPM:CRT1', 'SI-11M2:DI-BPM:CRT1',
            'SI-11C1:DI-BPM-1:CRT1', 'SI-11C1:DI-BPM-2:CRT1',
            'SI-11C2:DI-BPM:CRT1', 'SI-11C3:DI-BPM-1:CRT1',
            'SI-11C3:DI-BPM-2:CRT1', 'SI-11C4:DI-BPM:CRT1',

            'SI-12M1:DI-BPM:CRT1', 'SI-12M2:DI-BPM:CRT1',
            'SI-12C1:DI-BPM-1:CRT1', 'SI-12C1:DI-BPM-2:CRT1',
            'SI-12C2:DI-BPM:CRT1', 'SI-12C3:DI-BPM-1:CRT1',
            'SI-12C3:DI-BPM-2:CRT1', 'SI-12C4:DI-BPM:CRT1',

            'SI-13M1:DI-BPM:CRT1', 'SI-13M2:DI-BPM:CRT1',
            'SI-13C1:DI-BPM-1:CRT1', 'SI-13C1:DI-BPM-2:CRT1',
            'SI-13C2:DI-BPM:CRT1', 'SI-13C3:DI-BPM-1:CRT1',
            'SI-13C3:DI-BPM-2:CRT1', 'SI-13C4:DI-BPM:CRT1',

            'SI-14M1:DI-BPM:CRT1', 'SI-14M2:DI-BPM:CRT1',
            'SI-14C1:DI-BPM-1:CRT1', 'SI-14C1:DI-BPM-2:CRT1',
            'SI-14C2:DI-BPM:CRT1', 'SI-14C3:DI-BPM-1:CRT1',
            'SI-14C3:DI-BPM-2:CRT1', 'SI-14C4:DI-BPM:CRT1',

            'SI-15M1:DI-BPM:CRT1', 'SI-15M2:DI-BPM:CRT1',
            'SI-15C1:DI-BPM-1:CRT1', 'SI-15C1:DI-BPM-2:CRT1',
            'SI-15C2:DI-BPM:CRT1', 'SI-15C3:DI-BPM-1:CRT1',
            'SI-15C3:DI-BPM-2:CRT1', 'SI-15C4:DI-BPM:CRT1',

            'SI-16M1:DI-BPM:CRT1', 'SI-16M2:DI-BPM:CRT1',
            'SI-16C1:DI-BPM-1:CRT1', 'SI-16C1:DI-BPM-2:CRT1',
            'SI-16C2:DI-BPM:CRT1', 'SI-16C3:DI-BPM-1:CRT1',
            'SI-16C3:DI-BPM-2:CRT1', 'SI-16C4:DI-BPM:CRT1',

            'SI-17M1:DI-BPM:CRT1', 'SI-17M2:DI-BPM:CRT1',
            'SI-17C1:DI-BPM-1:CRT1', 'SI-17C1:DI-BPM-2:CRT1',
            'SI-17C2:DI-BPM:CRT1', 'SI-17C3:DI-BPM-1:CRT1',
            'SI-17C3:DI-BPM-2:CRT1', 'SI-17C4:DI-BPM:CRT1',

            'SI-18M1:DI-BPM:CRT1', 'SI-18M2:DI-BPM:CRT1',
            'SI-18C1:DI-BPM-1:CRT1', 'SI-18C1:DI-BPM-2:CRT1',
            'SI-18C2:DI-BPM:CRT1', 'SI-18C3:DI-BPM-1:CRT1',
            'SI-18C3:DI-BPM-2:CRT1', 'SI-18C4:DI-BPM:CRT1',

            'SI-19M1:DI-BPM:CRT1', 'SI-19M2:DI-BPM:CRT1',
            'SI-19C1:DI-BPM-1:CRT1', 'SI-19C1:DI-BPM-2:CRT1',
            'SI-19C2:DI-BPM:CRT1', 'SI-19C3:DI-BPM-1:CRT1',
            'SI-19C3:DI-BPM-2:CRT1', 'SI-19C4:DI-BPM:CRT1',

            'SI-20M1:DI-BPM:CRT1', 'SI-20M2:DI-BPM:CRT1',
            'SI-20C1:DI-BPM-1:CRT1', 'SI-20C1:DI-BPM-2:CRT1',
            'SI-20C2:DI-BPM:CRT1', 'SI-20C3:DI-BPM-1:CRT1',
            'SI-20C3:DI-BPM-2:CRT1', 'SI-20C4:DI-BPM:CRT1',
            ),
        },
    'SI-Fam:TI-BPM-PsMtn': {
        'database': {
            'Src': {'enums': ('FOFBS', 'PsMtn')},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'SI-01M1:DI-BPM:CRT2', 'SI-01M2:DI-BPM:CRT2',
            'SI-01C1:DI-BPM-1:CRT2', 'SI-01C1:DI-BPM-2:CRT2',
            'SI-01C2:DI-BPM:CRT2', 'SI-01C3:DI-BPM-1:CRT2',
            'SI-01C3:DI-BPM-2:CRT2', 'SI-01C4:DI-BPM:CRT2',

            'SI-02M1:DI-BPM:CRT2', 'SI-02M2:DI-BPM:CRT2',
            'SI-02C1:DI-BPM-1:CRT2', 'SI-02C1:DI-BPM-2:CRT2',
            'SI-02C2:DI-BPM:CRT2', 'SI-02C3:DI-BPM-1:CRT2',
            'SI-02C3:DI-BPM-2:CRT2', 'SI-02C4:DI-BPM:CRT2',

            'SI-03M1:DI-BPM:CRT2', 'SI-03M2:DI-BPM:CRT2',
            'SI-03C1:DI-BPM-1:CRT2', 'SI-03C1:DI-BPM-2:CRT2',
            'SI-03C2:DI-BPM:CRT2', 'SI-03C3:DI-BPM-1:CRT2',
            'SI-03C3:DI-BPM-2:CRT2', 'SI-03C4:DI-BPM:CRT2',

            'SI-04M1:DI-BPM:CRT2', 'SI-04M2:DI-BPM:CRT2',
            'SI-04C1:DI-BPM-1:CRT2', 'SI-04C1:DI-BPM-2:CRT2',
            'SI-04C2:DI-BPM:CRT2', 'SI-04C3:DI-BPM-1:CRT2',
            'SI-04C3:DI-BPM-2:CRT2', 'SI-04C4:DI-BPM:CRT2',

            'SI-05M1:DI-BPM:CRT2', 'SI-05M2:DI-BPM:CRT2',
            'SI-05C1:DI-BPM-1:CRT2', 'SI-05C1:DI-BPM-2:CRT2',
            'SI-05C2:DI-BPM:CRT2', 'SI-05C3:DI-BPM-1:CRT2',
            'SI-05C3:DI-BPM-2:CRT2', 'SI-05C4:DI-BPM:CRT2',

            'SI-06M1:DI-BPM:CRT2', 'SI-06M2:DI-BPM:CRT2',
            'SI-06C1:DI-BPM-1:CRT2', 'SI-06C1:DI-BPM-2:CRT2',
            'SI-06C2:DI-BPM:CRT2', 'SI-06C3:DI-BPM-1:CRT2',
            'SI-06C3:DI-BPM-2:CRT2', 'SI-06C4:DI-BPM:CRT2',

            'SI-07M1:DI-BPM:CRT2', 'SI-07M2:DI-BPM:CRT2',
            'SI-07C1:DI-BPM-1:CRT2', 'SI-07C1:DI-BPM-2:CRT2',
            'SI-07C2:DI-BPM:CRT2', 'SI-07C3:DI-BPM-1:CRT2',
            'SI-07C3:DI-BPM-2:CRT2', 'SI-07C4:DI-BPM:CRT2',

            'SI-08M1:DI-BPM:CRT2', 'SI-08M2:DI-BPM:CRT2',
            'SI-08C1:DI-BPM-1:CRT2', 'SI-08C1:DI-BPM-2:CRT2',
            'SI-08C2:DI-BPM:CRT2', 'SI-08C3:DI-BPM-1:CRT2',
            'SI-08C3:DI-BPM-2:CRT2', 'SI-08C4:DI-BPM:CRT2',

            'SI-09M1:DI-BPM:CRT2', 'SI-09M2:DI-BPM:CRT2',
            'SI-09C1:DI-BPM-1:CRT2', 'SI-09C1:DI-BPM-2:CRT2',
            'SI-09C2:DI-BPM:CRT2', 'SI-09C3:DI-BPM-1:CRT2',
            'SI-09C3:DI-BPM-2:CRT2', 'SI-09C4:DI-BPM:CRT2',

            'SI-10M1:DI-BPM:CRT2', 'SI-10M2:DI-BPM:CRT2',
            'SI-10C1:DI-BPM-1:CRT2', 'SI-10C1:DI-BPM-2:CRT2',
            'SI-10C2:DI-BPM:CRT2', 'SI-10C3:DI-BPM-1:CRT2',
            'SI-10C3:DI-BPM-2:CRT2', 'SI-10C4:DI-BPM:CRT2',

            'SI-11M1:DI-BPM:CRT2', 'SI-11M2:DI-BPM:CRT2',
            'SI-11C1:DI-BPM-1:CRT2', 'SI-11C1:DI-BPM-2:CRT2',
            'SI-11C2:DI-BPM:CRT2', 'SI-11C3:DI-BPM-1:CRT2',
            'SI-11C3:DI-BPM-2:CRT2', 'SI-11C4:DI-BPM:CRT2',

            'SI-12M1:DI-BPM:CRT2', 'SI-12M2:DI-BPM:CRT2',
            'SI-12C1:DI-BPM-1:CRT2', 'SI-12C1:DI-BPM-2:CRT2',
            'SI-12C2:DI-BPM:CRT2', 'SI-12C3:DI-BPM-1:CRT2',
            'SI-12C3:DI-BPM-2:CRT2', 'SI-12C4:DI-BPM:CRT2',

            'SI-13M1:DI-BPM:CRT2', 'SI-13M2:DI-BPM:CRT2',
            'SI-13C1:DI-BPM-1:CRT2', 'SI-13C1:DI-BPM-2:CRT2',
            'SI-13C2:DI-BPM:CRT2', 'SI-13C3:DI-BPM-1:CRT2',
            'SI-13C3:DI-BPM-2:CRT2', 'SI-13C4:DI-BPM:CRT2',

            'SI-14M1:DI-BPM:CRT2', 'SI-14M2:DI-BPM:CRT2',
            'SI-14C1:DI-BPM-1:CRT2', 'SI-14C1:DI-BPM-2:CRT2',
            'SI-14C2:DI-BPM:CRT2', 'SI-14C3:DI-BPM-1:CRT2',
            'SI-14C3:DI-BPM-2:CRT2', 'SI-14C4:DI-BPM:CRT2',

            'SI-15M1:DI-BPM:CRT2', 'SI-15M2:DI-BPM:CRT2',
            'SI-15C1:DI-BPM-1:CRT2', 'SI-15C1:DI-BPM-2:CRT2',
            'SI-15C2:DI-BPM:CRT2', 'SI-15C3:DI-BPM-1:CRT2',
            'SI-15C3:DI-BPM-2:CRT2', 'SI-15C4:DI-BPM:CRT2',

            'SI-16M1:DI-BPM:CRT2', 'SI-16M2:DI-BPM:CRT2',
            'SI-16C1:DI-BPM-1:CRT2', 'SI-16C1:DI-BPM-2:CRT2',
            'SI-16C2:DI-BPM:CRT2', 'SI-16C3:DI-BPM-1:CRT2',
            'SI-16C3:DI-BPM-2:CRT2', 'SI-16C4:DI-BPM:CRT2',

            'SI-17M1:DI-BPM:CRT2', 'SI-17M2:DI-BPM:CRT2',
            'SI-17C1:DI-BPM-1:CRT2', 'SI-17C1:DI-BPM-2:CRT2',
            'SI-17C2:DI-BPM:CRT2', 'SI-17C3:DI-BPM-1:CRT2',
            'SI-17C3:DI-BPM-2:CRT2', 'SI-17C4:DI-BPM:CRT2',

            'SI-18M1:DI-BPM:CRT2', 'SI-18M2:DI-BPM:CRT2',
            'SI-18C1:DI-BPM-1:CRT2', 'SI-18C1:DI-BPM-2:CRT2',
            'SI-18C2:DI-BPM:CRT2', 'SI-18C3:DI-BPM-1:CRT2',
            'SI-18C3:DI-BPM-2:CRT2', 'SI-18C4:DI-BPM:CRT2',

            'SI-19M1:DI-BPM:CRT2', 'SI-19M2:DI-BPM:CRT2',
            'SI-19C1:DI-BPM-1:CRT2', 'SI-19C1:DI-BPM-2:CRT2',
            'SI-19C2:DI-BPM:CRT2', 'SI-19C3:DI-BPM-1:CRT2',
            'SI-19C3:DI-BPM-2:CRT2', 'SI-19C4:DI-BPM:CRT2',

            'SI-20M1:DI-BPM:CRT2', 'SI-20M2:DI-BPM:CRT2',
            'SI-20C1:DI-BPM-1:CRT2', 'SI-20C1:DI-BPM-2:CRT2',
            'SI-20C2:DI-BPM:CRT2', 'SI-20C3:DI-BPM-1:CRT2',
            'SI-20C3:DI-BPM-2:CRT2', 'SI-20C4:DI-BPM:CRT2',
            ),
        },
    'SI-Fam:TI-FOFB': {
        'database': {
            'Src': {'enums': ('FOFBS', )},
            'Delay': {'value': 0.0},
            'RFDelayType': {'value': 1, 'states': (2, 0)},
            'NrPulses': {'value': 1},
            'Duration': {'value': 150},
            'State': {'value': 0},
            'Polarity': {'value': 0, 'states': (0, 1)},
            },
        'channels': (
            'IA-01RaBPM:BS-FOFBCtrl:CRT5',
            'IA-02RaBPM:BS-FOFBCtrl:CRT5',
            'IA-03RaBPM:BS-FOFBCtrl:CRT5',
            'IA-04RaBPM:BS-FOFBCtrl:CRT5',
            'IA-05RaBPM:BS-FOFBCtrl:CRT5',
            'IA-06RaBPM:BS-FOFBCtrl:CRT5',
            'IA-07RaBPM:BS-FOFBCtrl:CRT5',
            'IA-08RaBPM:BS-FOFBCtrl:CRT5',
            'IA-09RaBPM:BS-FOFBCtrl:CRT5',
            'IA-10RaBPM:BS-FOFBCtrl:CRT5',
            'IA-11RaBPM:BS-FOFBCtrl:CRT5',
            'IA-12RaBPM:BS-FOFBCtrl:CRT5',
            'IA-13RaBPM:BS-FOFBCtrl:CRT5',
            'IA-14RaBPM:BS-FOFBCtrl:CRT5',
            'IA-15RaBPM:BS-FOFBCtrl:CRT5',
            'IA-16RaBPM:BS-FOFBCtrl:CRT5',
            'IA-17RaBPM:BS-FOFBCtrl:CRT5',
            'IA-18RaBPM:BS-FOFBCtrl:CRT5',
            'IA-19RaBPM:BS-FOFBCtrl:CRT5',
            'IA-20RaBPM:BS-FOFBCtrl:CRT5',
            ),
        },
}
